[git]
[borg.target]
mode = "path"
target = "~/borg::archive"

# [git.target]
# mode = "gitconfig" # inherit, gitconfig, path
# target = "" # target is hard to be cross specified by `borg` etc. need further design

# [git.assets]
# Only triggerred when the super command is listed in `trigger_by`
# trigger_by = ["git", "borg"]
# The behavior when unsaved work is detected
# on_unsave = "save" # save, ignore, ask, interrupt
# The behavior when super command recursively found this child repo
# on_recursion = "inherit" # skip, include, s tan da lo ne, double, inherit
# The protocol to specify the target

# [git.heritage]
# When `true`, equivalent to force child as `on_recursion = "include"`
# ignore_child = false
# The config to be inherited by child if child was set as `on_recursion = "inherit"`
# Dev Note: should panic when canonicalize if it's set to `inherit`
# on_recursion = "skip" # skip, include, standalone, double
# The config to be inherited by child if child was set as `target_mode = "inherit"`

# [borg.assets]
# trigger_by = ["git", "borg"]
# on_recursion = "standalone" # skip, include, standalone, double, inherit

# [borg.target]
# mode = "path"
# target = "/borg::archive"

# [tar]

# [rsync]

# [NTFS]